import typing
import collections.abc
import typing_extensions
import numpy.typing as npt

def draw_entry(display_keymaps, entry, col, level=0) -> None: ...
def draw_filtered(display_keymaps, filter_type, filter_text, layout) -> None: ...
def draw_hierarchy(display_keymaps, layout) -> None: ...
def draw_keymaps(context, layout) -> None: ...
def draw_km(display_keymaps, kc, km, children, layout, level) -> None: ...
def draw_kmi(display_keymaps, kc, km, kmi, layout, level) -> None: ...
